services:
  pgsql:
    container_name: pgsql
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PGSQL_ADMIN_PASS}
      POSTGRES_USER: root
      POSTGRES_DB: postgres
    volumes:
      - ${PGSQL_VOLUME}:/var/lib/postgresql
    ports:
      - ${PGSQL_PORT_MAPPING}